# Generated by Django 3.0.6 on 2020-05-24 16:24

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_filed', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=11)),
                ('assigned_to', models.ForeignKey(on_delete=models.SET('User has been deleted'), related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(on_delete=models.SET('User has been deleted'), related_name='completed_by', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=models.SET('User has been deleted'), related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
