# Generated by Django 3.0.6 on 2020-05-24 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0002_workticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('User has been deleted'), related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workticket',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('User has been deleted'), related_name='completed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
